package routes

import (
	"sep/backend/internal/handlers"
	"sep/backend/internal/middleware"

	"github.com/gin-gonic/gin"
)

func Setup(r *gin.Engine, jwtSecret string) {
	// ENT-04: Global rate limit
	r.Use(middleware.RateLimit())

	v1 := r.Group("/api/v1")

	// Health & Readiness (Phase 23 — no auth required)
	v1.GET("/health", handlers.HealthCheck)
	v1.GET("/ready", handlers.ReadinessCheck)

	// IOT-01: WebSocket (no auth — client sends token after connect)
	r.GET("/ws", handlers.WSHandler)

	// Public routes (with auth-specific rate limit)
	auth := v1.Group("/auth")
	auth.Use(middleware.AuthRateLimit())
	{
		auth.POST("/login", handlers.Login)
	}

	// Protected routes
	protected := v1.Group("")
	protected.Use(middleware.AuthMiddleware(jwtSecret))
	{
		// Shorthand for per-menu permission gating (view/add/edit/delete tiers)
		mp := middleware.MenuPermission

		protected.POST("/auth/logout", handlers.Logout)
		protected.GET("/auth/me", handlers.Me)
		protected.PUT("/auth/password", handlers.ChangePassword)

		// RBAC & User Management (Phase 19)
		protected.GET("/rbac/users", mp("settings.users", "view"), handlers.GetUsers)
		protected.POST("/rbac/users", mp("settings.users", "add"), handlers.CreateUser)
		protected.PUT("/rbac/users/:id", mp("settings.users", "edit"), handlers.UpdateUser)
		protected.PATCH("/rbac/users/:id/toggle-active", mp("settings.users", "edit"), handlers.ToggleUserActive)
		protected.POST("/rbac/users/:id/reset-password", mp("settings.users", "edit"), handlers.AdminResetPassword)
		protected.GET("/rbac/access-logs", mp("settings.logs", "view"), handlers.GetAccessLogs)
		protected.GET("/rbac/companies", mp("settings.company", "view"), handlers.GetCompanies)
		protected.POST("/rbac/companies", mp("settings.company", "add"), handlers.CreateCompany)
		// NOTE: /rbac/menu-permissions GET is NOT gated by mp() — every authenticated user of
		// any role fetches their own menu permissions here on app load (authStore.loadMenuPermissions),
		// so this must stay open to all roles, not just settings.roles-tiered ones.
		protected.GET("/rbac/menu-permissions", handlers.GetMenuPermissions)
		protected.POST("/rbac/menu-permissions", middleware.RoleRequired("superadmin", "admin"), mp("settings.roles", "edit"), handlers.UpdateMenuPermissions)
		protected.GET("/rbac/users/:id/menu-permissions", middleware.RoleRequired("superadmin", "admin"), mp("settings.users", "view"), handlers.GetUserMenuPermissions)
		protected.POST("/rbac/users/:id/menu-permissions", middleware.RoleRequired("superadmin", "admin"), mp("settings.users", "edit"), handlers.UpdateUserMenuPermissions)

		// Dashboard
		protected.GET("/dashboard/kpi", handlers.DashboardKPI)
		protected.GET("/dashboard/alerts", handlers.DashboardAlerts)
		protected.GET("/dashboard/oee", handlers.OEERealtimeData)

		// Factory (Phase 5) — gated per-menu (view/add/edit tiers); delete is superadmin-only
		protected.GET("/factory/workorders", mp("factory.workorder", "view"), handlers.GetWorkOrders)
		protected.POST("/factory/workorders", mp("factory.workorder", "add"), handlers.CreateWorkOrder)
		protected.PATCH("/factory/workorders/:id/qty", mp("factory.workorder", "edit"), handlers.UpdateWorkOrderQty)
		protected.GET("/factory/machines", mp("factory.machines", "view"), handlers.GetMachines)
		protected.POST("/factory/machines", mp("factory.machines", "add"), handlers.CreateMachine)
		protected.PUT("/factory/machines/:id", mp("factory.machines", "edit"), handlers.UpdateMachine)
		protected.GET("/factory/bom", mp("factory.bom", "view"), handlers.GetBOM)
		protected.POST("/factory/bom", mp("factory.bom", "add"), handlers.CreateBOM)
		protected.GET("/factory/downtime", mp("factory.downtime", "view"), handlers.GetDowntime)
		protected.POST("/factory/downtime", mp("factory.downtime", "add"), handlers.CreateDowntime)

		// Factory Lanjutan (Phase 31) — Work Centers, Routing, OEE Real, Scrap, Capacity, Reports
		protected.GET("/factory/workcenters", mp("factory.workcenters", "view"), handlers.GetWorkCenters)
		protected.POST("/factory/workcenters", mp("factory.workcenters", "add"), handlers.CreateWorkCenter)
		protected.PUT("/factory/workcenters/:id", mp("factory.workcenters", "edit"), handlers.UpdateWorkCenter)
		protected.DELETE("/factory/workcenters/:id", mp("factory.workcenters", "delete"), handlers.DeleteWorkCenter)
		protected.GET("/factory/routings", mp("factory.routing", "view"), handlers.GetProductRoutings)
		protected.POST("/factory/routings", mp("factory.routing", "add"), handlers.CreateProductRouting)
		protected.PUT("/factory/routings/:id", mp("factory.routing", "edit"), handlers.UpdateProductRouting)
		protected.DELETE("/factory/routings/:id", mp("factory.routing", "delete"), handlers.DeleteProductRouting)
		protected.GET("/factory/oee-real", mp("factory.oee", "view"), handlers.GetOEEReal)
		protected.GET("/factory/scrap", mp("factory.scrap", "view"), handlers.GetScrapRework)
		protected.POST("/factory/scrap", mp("factory.scrap", "add"), handlers.CreateScrapRework)
		protected.GET("/factory/capacity", mp("factory.capacity", "view"), handlers.GetCapacityPlan)
		protected.GET("/factory/report", mp("factory.report", "view"), handlers.GetProductionReport)
		protected.GET("/factory/downtime-analysis", mp("factory.downtime", "view"), handlers.GetDowntimeAnalysis)

		// HRIS — gated per-menu (view/add/edit tiers); delete is superadmin-only
		protected.GET("/hris/employees", mp("hris.employee", "view"), handlers.GetEmployees)
		protected.POST("/hris/employees", mp("hris.employee", "add"), handlers.CreateEmployee)
		protected.PUT("/hris/employees/:id", mp("hris.employee", "edit"), handlers.UpdateEmployee)
		protected.DELETE("/hris/employees/:id", mp("hris.employee", "delete"), handlers.DeleteEmployee)
		protected.GET("/hris/attendance", mp("hris.attendance", "view"), handlers.GetAttendance)
		protected.POST("/hris/attendance/checkin", mp("hris.attendance", "edit"), handlers.CheckInAttendance)
		protected.PATCH("/hris/attendance/:id/checkout", mp("hris.attendance", "edit"), handlers.CheckOutAttendance)
		protected.GET("/hris/leaves", mp("hris.leave", "view"), handlers.GetLeaveRequests)
		protected.POST("/hris/leaves", mp("hris.leave", "add"), handlers.CreateLeaveRequest)
		protected.PATCH("/hris/leaves/:id/status", mp("hris.leave", "edit"), handlers.UpdateLeaveStatus)
		protected.GET("/hris/payroll", mp("hris.payroll", "view"), handlers.GetPayroll)
		protected.POST("/hris/payroll/generate", mp("hris.payroll", "add"), handlers.GeneratePayroll)
		protected.PATCH("/hris/payroll/:id/status", mp("hris.payroll", "edit"), handlers.UpdatePayrollStatus)
		// HRIS Advanced (Phase 16)
		protected.GET("/hris/jobs", mp("hris.recruitment", "view"), handlers.GetJobPostings)
		protected.POST("/hris/jobs", mp("hris.recruitment", "add"), handlers.CreateJobPosting)
		protected.PATCH("/hris/jobs/:id/status", mp("hris.recruitment", "edit"), handlers.UpdateJobPosting)
		protected.DELETE("/hris/jobs/:id", mp("hris.recruitment", "delete"), handlers.DeleteJobPosting)
		protected.GET("/hris/candidates", mp("hris.recruitment", "view"), handlers.GetCandidates)
		protected.POST("/hris/candidates", mp("hris.recruitment", "add"), handlers.CreateCandidate)
		protected.PATCH("/hris/candidates/:id/stage", mp("hris.recruitment", "edit"), handlers.UpdateCandidateStage)
		protected.DELETE("/hris/candidates/:id", mp("hris.recruitment", "delete"), handlers.DeleteCandidate)
		protected.GET("/hris/training/programs", mp("hris.training", "view"), handlers.GetTrainingPrograms)
		protected.POST("/hris/training/programs", mp("hris.training", "add"), handlers.CreateTrainingProgram)
		protected.DELETE("/hris/training/programs/:id", mp("hris.training", "delete"), handlers.DeleteTrainingProgram)
		protected.GET("/hris/training/schedules", mp("hris.training", "view"), handlers.GetTrainingSchedules)
		protected.POST("/hris/training/schedules", mp("hris.training", "add"), handlers.CreateTrainingSchedule)
		protected.PATCH("/hris/training/schedules/:id/status", mp("hris.training", "edit"), handlers.UpdateTrainingStatus)
		protected.GET("/hris/kpi/templates", mp("hris.kpi", "view"), handlers.GetKPITemplates)
		protected.POST("/hris/kpi/templates", mp("hris.kpi", "add"), handlers.CreateKPITemplate)
		protected.DELETE("/hris/kpi/templates/:id", mp("hris.kpi", "delete"), handlers.DeleteKPITemplate)
		protected.GET("/hris/kpi/reviews", mp("hris.kpi", "view"), handlers.GetKPIReviews)
		protected.POST("/hris/kpi/reviews", mp("hris.kpi", "add"), handlers.CreateKPIReview)
		protected.GET("/hris/shifts", mp("hris.overtime", "view"), handlers.GetShifts)
		protected.POST("/hris/shifts", mp("hris.overtime", "add"), handlers.CreateShift)
		protected.DELETE("/hris/shifts/:id", mp("hris.overtime", "delete"), handlers.DeleteShift)
		protected.GET("/hris/overtime", mp("hris.overtime", "view"), handlers.GetOvertimeRecords)
		protected.POST("/hris/overtime", mp("hris.overtime", "add"), handlers.CreateOvertimeRecord)
		protected.PATCH("/hris/overtime/:id/status", mp("hris.overtime", "edit"), handlers.UpdateOvertimeStatus)

		// HRIS Completion (Phase 32) — HR Dashboard, Org Chart, Payslip, Attendance Calendar
		protected.GET("/hris/dashboard", mp("hris.hrdashboard", "view"), handlers.GetHRDashboard)
		protected.GET("/hris/orgchart", mp("hris.orgchart", "view"), handlers.GetOrgChart)
		protected.GET("/hris/payslip", mp("hris.payslip", "view"), handlers.GetPayslipHistory)
		protected.GET("/hris/payslip/:id", mp("hris.payslip", "view"), handlers.GetPayslip)
		protected.GET("/hris/attendance-calendar", mp("hris.attendance", "view"), handlers.GetAttendanceCalendar)

		// Warehouse (Phase 4) — gated per-menu (view/add/edit tiers); delete is superadmin-only
		protected.GET("/warehouse/inventory", mp("warehouse.inventory", "view"), handlers.GetInventory)
		protected.POST("/warehouse/inventory", mp("warehouse.inventory", "add"), handlers.CreateInventory)
		protected.PUT("/warehouse/inventory/:id", mp("warehouse.inventory", "edit"), handlers.UpdateInventory)
		protected.DELETE("/warehouse/inventory/:id", mp("warehouse.inventory", "delete"), handlers.DeleteInventory)
		protected.PUT("/warehouse/inventory/:id/qty", mp("warehouse.inventory", "edit"), handlers.UpdateInventoryQty)
		protected.GET("/warehouse/movements", mp("warehouse.movements", "view"), handlers.GetMovements)
		protected.POST("/warehouse/movements", mp("warehouse.movements", "add"), handlers.CreateMovement)
		protected.GET("/warehouse/alerts", mp("warehouse.alerts", "view"), handlers.GetStockAlerts)
		protected.POST("/warehouse/transfer", mp("warehouse.inventory", "edit"), handlers.CreateStockTransfer)
		protected.GET("/warehouse/opname", mp("warehouse.opname", "view"), handlers.GetStockOpname)
		protected.POST("/warehouse/opname", mp("warehouse.opname", "add"), handlers.SubmitStockOpname)

		// Asset
		protected.GET("/asset/assets", mp("asset.assets", "view"), handlers.GetAssets)
		protected.POST("/asset/assets", mp("asset.assets", "add"), handlers.CreateAsset)
		protected.PUT("/asset/assets/:id", mp("asset.assets", "edit"), handlers.UpdateAsset)
		protected.DELETE("/asset/assets/:id", mp("asset.assets", "delete"), handlers.DeleteAsset)
		protected.GET("/asset/maintenance", mp("asset.maintenance", "view"), handlers.GetMaintenanceSchedule)
		protected.POST("/asset/maintenance", mp("asset.maintenance", "add"), handlers.CreateMaintenance)
		protected.PATCH("/asset/maintenance/:id/status", mp("asset.maintenance", "edit"), handlers.UpdateMaintenanceStatus)
		// Asset CMMS (Phase 17)
		protected.GET("/asset/pm", mp("asset.pm", "view"), handlers.GetPMSchedules)
		protected.POST("/asset/pm", mp("asset.pm", "add"), handlers.CreatePMSchedule)
		protected.PUT("/asset/pm/:id", mp("asset.pm", "edit"), handlers.UpdatePMSchedule)
		protected.DELETE("/asset/pm/:id", mp("asset.pm", "delete"), handlers.DeletePMSchedule)
		protected.GET("/asset/spareparts", mp("asset.spareparts", "view"), handlers.GetSpareParts)
		protected.POST("/asset/spareparts", mp("asset.spareparts", "add"), handlers.CreateSparePart)
		protected.PUT("/asset/spareparts/:id", mp("asset.spareparts", "edit"), handlers.UpdateSparePart)
		protected.DELETE("/asset/spareparts/:id", mp("asset.spareparts", "delete"), handlers.DeleteSparePart)
		protected.GET("/asset/depreciation", mp("asset.depreciation", "view"), handlers.GetDepreciation)
		protected.POST("/asset/depreciation/calculate", mp("asset.depreciation", "add"), handlers.CalculateDepreciation)
		protected.GET("/asset/disposals", mp("asset.depreciation", "view"), handlers.GetDisposals)
		protected.POST("/asset/disposals", mp("asset.depreciation", "add"), handlers.CreateDisposal)

		// Purchasing — gated per-menu (view/add/edit tiers); delete is superadmin-only
		protected.GET("/purchasing/pr", mp("purchasing.pr", "view"), handlers.GetPurchaseRequests)
		protected.POST("/purchasing/pr", mp("purchasing.pr", "add"), handlers.CreatePurchaseRequest)
		protected.PATCH("/purchasing/pr/:id/status", mp("purchasing.pr", "edit"), handlers.UpdatePRStatus)
		protected.POST("/purchasing/pr/:id/convert", mp("purchasing.pr", "edit"), handlers.ConvertPRtoPO)
		protected.DELETE("/purchasing/pr/:id", mp("purchasing.pr", "delete"), handlers.DeletePurchaseRequest)
		protected.GET("/purchasing/po", mp("purchasing.po", "view"), handlers.GetPurchaseOrders)
		protected.POST("/purchasing/po", mp("purchasing.po", "add"), handlers.CreatePurchaseOrder)
		protected.DELETE("/purchasing/po/:id", mp("purchasing.po", "delete"), handlers.DeletePurchaseOrder)
		protected.GET("/purchasing/grn", mp("purchasing.grn", "view"), handlers.GetGRN)
		protected.POST("/purchasing/grn", mp("purchasing.grn", "add"), handlers.CreateGRN)
		protected.GET("/purchasing/vendors", mp("purchasing.vendor", "view"), handlers.GetVendors)
		protected.POST("/purchasing/vendors", mp("purchasing.vendor", "add"), handlers.CreateVendor)
		protected.PUT("/purchasing/vendors/:id", mp("purchasing.vendor", "edit"), handlers.UpdateVendor)
		protected.DELETE("/purchasing/vendors/:id", mp("purchasing.vendor", "delete"), handlers.DeleteVendor)
		protected.GET("/purchasing/rfq", mp("purchasing.rfq", "view"), handlers.GetRFQs)
		protected.POST("/purchasing/rfq", mp("purchasing.rfq", "add"), handlers.CreateRFQ)
		protected.DELETE("/purchasing/rfq/:id", mp("purchasing.rfq", "delete"), handlers.DeleteRFQ)
		protected.POST("/purchasing/rfq/:id/send", mp("purchasing.rfq", "edit"), handlers.SendRFQ)
		protected.GET("/purchasing/rfq/:id/vendors", mp("purchasing.rfq", "view"), handlers.GetRFQVendors)
		protected.GET("/purchasing/rfq/:id/offers", mp("purchasing.rfq", "view"), handlers.GetRFQOffers)
		protected.POST("/purchasing/rfq/:id/offers", mp("purchasing.rfq", "add"), handlers.SubmitOffer)
		protected.POST("/purchasing/rfq/:id/select-winner", mp("purchasing.rfq", "edit"), handlers.SelectRFQWinner)

		// Sales (Phase 10) — gated per-menu (view/add/edit tiers); delete is superadmin-only
		protected.GET("/sales/customers", mp("sales.customer", "view"), handlers.GetCustomers)
		protected.POST("/sales/customers", mp("sales.customer", "add"), handlers.CreateCustomer)
		protected.PUT("/sales/customers/:id", mp("sales.customer", "edit"), handlers.UpdateCustomer)
		protected.DELETE("/sales/customers/:id", mp("sales.customer", "delete"), handlers.DeleteCustomer)
		protected.GET("/sales/orders", mp("sales.so", "view"), handlers.GetSalesOrders)
		protected.POST("/sales/orders", mp("sales.so", "add"), handlers.CreateSalesOrder)
		protected.GET("/sales/orders/:id", mp("sales.so", "view"), handlers.GetSalesOrderDetail)
		protected.PATCH("/sales/orders/:id/status", mp("sales.so", "edit"), handlers.UpdateSOStatus)
		protected.DELETE("/sales/orders/:id", mp("sales.so", "delete"), handlers.DeleteSalesOrder)
		protected.GET("/sales/delivery", mp("sales.do", "view"), handlers.GetDeliveryOrders)
		protected.POST("/sales/delivery", mp("sales.do", "add"), handlers.CreateDelivery)
		protected.PATCH("/sales/delivery/:id/confirm", mp("sales.do", "edit"), handlers.ConfirmDelivery)
		protected.GET("/sales/invoices", mp("sales.invoice", "view"), handlers.GetInvoices)
		protected.POST("/sales/invoices", mp("sales.invoice", "add"), handlers.CreateInvoice)

		// Sales Phase 24 — Quotation, Returns, CRM
		protected.GET("/sales/quotations", mp("sales.quotation", "view"), handlers.GetQuotations)
		protected.POST("/sales/quotations", mp("sales.quotation", "add"), handlers.CreateQuotation)
		protected.PATCH("/sales/quotations/:id/status", mp("sales.quotation", "edit"), handlers.UpdateQuotationStatus)
		protected.POST("/sales/quotations/:id/convert", mp("sales.quotation", "edit"), handlers.ConvertQuotationToSO)
		protected.GET("/sales/returns", mp("sales.retur", "view"), handlers.GetSalesReturns)
		protected.POST("/sales/returns", mp("sales.retur", "add"), handlers.CreateSalesReturn)
		protected.PATCH("/sales/returns/:id/confirm", mp("sales.retur", "edit"), handlers.ConfirmSalesReturn)
		protected.GET("/sales/crm/leads", mp("sales.crm", "view"), handlers.GetLeads)
		protected.POST("/sales/crm/leads", mp("sales.crm", "add"), handlers.CreateLead)
		protected.PUT("/sales/crm/leads/:id", mp("sales.crm", "edit"), handlers.UpdateLead)
		protected.PATCH("/sales/crm/leads/:id/stage", mp("sales.crm", "edit"), handlers.UpdateLeadStage)
		protected.GET("/sales/crm/activities", mp("sales.crm", "view"), handlers.GetCRMActivities)
		protected.POST("/sales/crm/activities", mp("sales.crm", "add"), handlers.CreateCRMActivity)
		protected.GET("/sales/crm/stats", mp("sales.crm", "view"), handlers.GetCRMStats)

		// Quality Management (Phase 14) — gated per-menu (view/add/edit tiers); delete is superadmin-only
		protected.GET("/qms/stats", mp("qms.inspeksi", "view"), handlers.GetQCStats)
		protected.GET("/qms/inspections", mp("qms.inspeksi", "view"), handlers.GetInspections)
		protected.POST("/qms/inspections", mp("qms.inspeksi", "add"), handlers.CreateInspection)
		protected.PATCH("/qms/inspections/:id/result", mp("qms.inspeksi", "edit"), handlers.UpdateInspectionResult)
		protected.DELETE("/qms/inspections/:id", mp("qms.inspeksi", "delete"), handlers.DeleteInspection)
		protected.GET("/qms/ncr", mp("qms.ncr", "view"), handlers.GetNCRs)
		protected.POST("/qms/ncr", mp("qms.ncr", "add"), handlers.CreateNCR)
		protected.PATCH("/qms/ncr/:id/status", mp("qms.ncr", "edit"), handlers.UpdateNCRStatus)
		protected.DELETE("/qms/ncr/:id", mp("qms.ncr", "delete"), handlers.DeleteNCR)
		protected.GET("/qms/capa", mp("qms.capa", "view"), handlers.GetCAPAs)
		protected.POST("/qms/capa", mp("qms.capa", "add"), handlers.CreateCAPA)
		protected.PATCH("/qms/capa/:id/status", mp("qms.capa", "edit"), handlers.UpdateCAPAStatus)
		protected.GET("/qms/tools", mp("qms.kalibrasi", "view"), handlers.GetMeasuringTools)
		protected.POST("/qms/tools", mp("qms.kalibrasi", "add"), handlers.CreateMeasuringTool)
		protected.PATCH("/qms/tools/:id/calibrate", mp("qms.kalibrasi", "edit"), handlers.RecordCalibration)
		protected.DELETE("/qms/tools/:id", mp("qms.kalibrasi", "delete"), handlers.DeleteMeasuringTool)
		protected.GET("/qms/calibration-alerts", mp("qms.kalibrasi", "view"), handlers.GetCalibrationAlerts)

		// MRP & Production Planning (Phase 13)
		protected.GET("/mrp/runs", mp("mrp.engine", "view"), handlers.GetMRPRuns)
		protected.POST("/mrp/runs", mp("mrp.engine", "add"), handlers.RunMRP)
		protected.GET("/mrp/results", mp("mrp.engine", "view"), handlers.GetMRPResults)
		protected.GET("/mrp/exceptions", mp("mrp.engine", "view"), handlers.GetMRPExceptions)
		protected.GET("/mrp/schedules", mp("mrp.jadwal", "view"), handlers.GetProductionSchedules)
		protected.POST("/mrp/schedules", mp("mrp.jadwal", "add"), handlers.CreateProductionSchedule)
		protected.PATCH("/mrp/schedules/:id/status", mp("mrp.jadwal", "edit"), handlers.UpdateScheduleStatus)
		protected.DELETE("/mrp/schedules/:id", mp("mrp.jadwal", "delete"), handlers.DeleteProductionSchedule)
		protected.GET("/mrp/routings", mp("mrp.routing", "view"), handlers.GetRoutings)
		protected.POST("/mrp/routings", mp("mrp.routing", "add"), handlers.CreateRouting)
		protected.PUT("/mrp/routings/:id", mp("mrp.routing", "edit"), handlers.UpdateRouting)
		protected.DELETE("/mrp/routings/:id", mp("mrp.routing", "delete"), handlers.DeleteRouting)
		protected.GET("/mrp/lots", mp("mrp.lot", "view"), handlers.GetLotNumbers)
		protected.POST("/mrp/lots", mp("mrp.lot", "add"), handlers.CreateLotNumber)
		protected.DELETE("/mrp/lots/:id", mp("mrp.lot", "delete"), handlers.DeleteLotNumber)

			// Cost Accounting (Phase 15)
			protected.GET("/cost/centers", mp("cost.centers", "view"), handlers.GetCostCenters)
			protected.POST("/cost/centers", mp("cost.centers", "add"), handlers.CreateCostCenter)
			protected.PUT("/cost/centers/:id", mp("cost.centers", "edit"), handlers.UpdateCostCenter)
			protected.DELETE("/cost/centers/:id", mp("cost.centers", "delete"), handlers.DeleteCostCenter)
			protected.GET("/cost/wo-costs", mp("cost.wo", "view"), handlers.GetWOCosts)
			protected.POST("/cost/wo-costs", mp("cost.wo", "add"), handlers.CreateWOCost)
			protected.DELETE("/cost/wo-costs/:id", mp("cost.wo", "delete"), handlers.DeleteWOCost)
			protected.GET("/cost/standard-costs", mp("cost.std", "view"), handlers.GetStandardCosts)
			protected.POST("/cost/standard-costs", mp("cost.std", "add"), handlers.UpsertStandardCost)
			protected.DELETE("/cost/standard-costs/:id", mp("cost.std", "delete"), handlers.DeleteStandardCost)
			protected.GET("/cost/variance", mp("cost.laporan", "view"), handlers.GetCostVariance)
			protected.GET("/cost/cogs", mp("cost.laporan", "view"), handlers.GetCOGSReport)
			protected.GET("/cost/profitability", mp("cost.laporan", "view"), handlers.GetProfitabilityReport)
			protected.GET("/cost/center-report", mp("cost.laporan", "view"), handlers.GetCostCenterReport)
			protected.GET("/cost/summary", mp("cost.laporan", "view"), handlers.GetCostSummary)

			// Tax & Compliance (Phase 12) — gated per-menu (view/add/edit tiers); delete is superadmin-only
		protected.GET("/tax/configs", mp("tax.config", "view"), handlers.GetTaxConfigs)
		protected.POST("/tax/configs", mp("tax.config", "edit"), handlers.UpsertTaxConfig)
		protected.GET("/tax/faktur-keluaran", mp("tax.ppn", "view"), handlers.GetFakturPajakKeluaran)
		protected.GET("/tax/faktur-masukan", mp("tax.ppn", "view"), handlers.GetFakturPajakMasukan)
		protected.GET("/tax/ppn-rekap", mp("tax.ppn", "view"), handlers.GetRekapPPN)
		protected.GET("/tax/pph21", mp("tax.pph21", "view"), handlers.GetPPh21)
		protected.POST("/tax/pph21/generate", mp("tax.pph21", "add"), handlers.GeneratePPh21)
		protected.DELETE("/tax/pph21/:id", mp("tax.pph21", "delete"), handlers.DeletePPh21)
		protected.GET("/tax/pph23", mp("tax.pph23", "view"), handlers.GetPPh23)
		protected.POST("/tax/pph23", mp("tax.pph23", "add"), handlers.CreatePPh23)
		protected.DELETE("/tax/pph23/:id", mp("tax.pph23", "delete"), handlers.DeletePPh23)
		protected.GET("/tax/bpjs", mp("tax.bpjs", "view"), handlers.GetBPJS)
		protected.POST("/tax/bpjs/generate", mp("tax.bpjs", "add"), handlers.GenerateBPJS)
		protected.DELETE("/tax/bpjs/:id", mp("tax.bpjs", "delete"), handlers.DeleteBPJS)

		// Budget & Financial Planning (Phase 18)
		protected.GET("/budget/entries", mp("budget.master", "view"), handlers.GetBudgets)
		protected.POST("/budget/entries", mp("budget.master", "add"), handlers.CreateBudget)
		protected.POST("/budget/entries/import", mp("budget.master", "add"), handlers.ImportBudgetEntries)
		protected.GET("/budget/entries/template", mp("budget.master", "view"), handlers.GetBudgetTemplate)
		protected.PUT("/budget/entries/:id", mp("budget.master", "edit"), handlers.UpdateBudget)
		protected.DELETE("/budget/entries/:id", mp("budget.master", "delete"), handlers.DeleteBudget)
		protected.PATCH("/budget/entries/:id/submit", mp("budget.master", "edit"), handlers.SubmitBudget)
		protected.PATCH("/budget/entries/:id/approve", mp("budget.master", "edit"), handlers.ApproveBudget)
		protected.PATCH("/budget/entries/:id/reject", mp("budget.master", "edit"), handlers.RejectBudget)
		protected.GET("/budget/vs-actual", mp("budget.vsactual", "view"), handlers.GetBudgetVsActual)
		protected.GET("/budget/alerts", mp("budget.alerts", "view"), handlers.GetBudgetAlerts)
		protected.GET("/budget/forecast", mp("budget.forecast", "view"), handlers.GetBudgetForecast)
		protected.GET("/budget/scenarios", mp("budget.scenarios", "view"), handlers.GetBudgetScenarios)
		protected.POST("/budget/scenarios", mp("budget.scenarios", "add"), handlers.CreateBudgetScenario)
		protected.PUT("/budget/scenarios/:id", mp("budget.scenarios", "edit"), handlers.UpdateBudgetScenario)
		protected.DELETE("/budget/scenarios/:id", mp("budget.scenarios", "delete"), handlers.DeleteBudgetScenario)

		// Approval Workflow Engine
		protected.GET("/approvals/pending", handlers.GetMyApprovals)
		protected.GET("/approvals/history", handlers.GetApprovalHistory)
		protected.GET("/approvals/:id", handlers.GetApprovalRequest)
		protected.PATCH("/approvals/:id/action", handlers.ActOnApproval)
		protected.GET("/approvals/rules", middleware.RoleRequired("superadmin", "admin"), handlers.GetApprovalRules)
		protected.POST("/approvals/rules", middleware.RoleRequired("superadmin", "admin"), handlers.CreateApprovalRule)
		protected.PUT("/approvals/rules/:id", middleware.RoleRequired("superadmin", "admin"), handlers.UpdateApprovalRule)
		protected.DELETE("/approvals/rules/:id", middleware.RoleRequired("superadmin", "admin"), handlers.DeleteApprovalRule)

		// Import / Export & API Publik (Phase 29)
		protected.GET("/integration/import/templates", handlers.GetImportTemplates)
		protected.GET("/integration/import/templates/:type/download", handlers.DownloadTemplate)
		protected.POST("/integration/import/preview", handlers.PreviewImport)
		protected.POST("/integration/import/execute", handlers.ExecuteImport)
		protected.GET("/integration/import/history", handlers.GetImportHistory)
		protected.GET("/integration/export/:type", handlers.ExportData)
		protected.GET("/integration/api-keys", handlers.GetAPIKeys)
		protected.POST("/integration/api-keys", handlers.CreateAPIKey)
		protected.DELETE("/integration/api-keys/:id", handlers.RevokeAPIKey)
		protected.GET("/integration/api-keys/logs", handlers.GetAPIUsageLogs)
		protected.GET("/integration/webhooks", handlers.GetWebhooks)
		protected.POST("/integration/webhooks", handlers.CreateWebhook)
		protected.PUT("/integration/webhooks/:id", handlers.UpdateWebhook)
		protected.DELETE("/integration/webhooks/:id", handlers.DeleteWebhook)
		protected.GET("/integration/webhooks/:id/logs", handlers.GetWebhookLogs)
		protected.GET("/integration/webhook-events", handlers.GetWebhookEvents)

		// Coretax DJP & e-Faktur (Phase 28) — gated per-menu (view/add/edit tiers)
		protected.GET("/tax/nsfp", mp("tax.nsfp", "view"), handlers.GetNSFP)
		protected.POST("/tax/nsfp/import", mp("tax.nsfp", "add"), handlers.ImportNSFP)
		protected.GET("/tax/efaktur", mp("tax.efaktur", "view"), handlers.GetEFaktur)
		protected.GET("/tax/efaktur/:id/xml", mp("tax.efaktur", "view"), handlers.GetEFakturXML)
		protected.GET("/tax/efaktur/export-csv", mp("tax.efaktur", "view"), handlers.ExportEFakturCSV)
		protected.POST("/tax/efaktur/:id/upload", mp("tax.efaktur", "edit"), handlers.UploadEFakturCoretax)
		protected.GET("/tax/spt-ppn", mp("tax.spt-ppn", "view"), handlers.GetSPTPPN)
		protected.POST("/tax/spt-ppn/submit", mp("tax.spt-ppn", "edit"), handlers.SubmitSPTPPN)

		// Bank Rekonsiliasi & Petty Cash (Phase 27) — part of Finance.jsx's Rekonsiliasi/Petty Cash tabs
		protected.GET("/recon/sessions", mp("finance.recon", "view"), handlers.GetReconSessions)
		protected.POST("/recon/sessions", mp("finance.recon", "add"), handlers.CreateReconSession)
		protected.GET("/recon/sessions/:id", mp("finance.recon", "view"), handlers.GetReconDetail)
		protected.POST("/recon/sessions/:id/auto-match", mp("finance.recon", "edit"), handlers.AutoMatch)
		protected.POST("/recon/sessions/:id/manual-match", mp("finance.recon", "edit"), handlers.ManualMatch)
		protected.PATCH("/recon/sessions/:id/lock", mp("finance.recon", "edit"), handlers.LockRecon)
		protected.GET("/petty-cash", mp("finance.petty-cash", "view"), handlers.GetPettyCash)
		protected.POST("/petty-cash", mp("finance.petty-cash", "add"), handlers.CreatePettyCash)
		protected.GET("/petty-cash/transactions", mp("finance.petty-cash", "view"), handlers.GetPettyCashTransactions)
		protected.POST("/petty-cash/transactions", mp("finance.petty-cash", "add"), handlers.CreatePettyCashTransaction)
		protected.POST("/petty-cash/:id/replenish", mp("finance.petty-cash", "edit"), handlers.ReplenishPettyCash)

		// Finance GL & Closing (Phase 25) — gated per-menu (view/add/edit tiers)
		protected.GET("/finance/gl", mp("accounting.gl", "view"), handlers.GetGeneralLedger)
		protected.GET("/finance/trial-balance", mp("accounting.trial-balance", "view"), handlers.GetTrialBalance)
		protected.GET("/finance/cashflow", mp("accounting.cashflow", "view"), handlers.GetCashFlow)
		protected.GET("/finance/periods", mp("accounting.closing", "view"), handlers.GetAccountingPeriods)
		protected.PATCH("/finance/periods/:id/close", mp("accounting.closing", "edit"), handlers.ClosePeriod)
		protected.PATCH("/finance/periods/:id/reopen", mp("accounting.closing", "edit"), handlers.ReopenPeriod)
		protected.GET("/finance/comparative/income-statement", mp("accounting.comparative", "view"), handlers.GetComparativeIncomeStatement)
		protected.GET("/finance/comparative/balance-sheet", mp("accounting.comparative", "view"), handlers.GetComparativeBalanceSheet)

		// Finance — AP/AR/Cash (Phase 11) — gated per-menu (view/add/edit tiers); delete is superadmin-only
		protected.GET("/finance/bank-accounts", mp("finance.bank", "view"), handlers.GetBankAccounts)
		protected.POST("/finance/bank-accounts", mp("finance.bank", "add"), handlers.CreateBankAccount)
		protected.PUT("/finance/bank-accounts/:id", mp("finance.bank", "edit"), handlers.UpdateBankAccount)
		protected.DELETE("/finance/bank-accounts/:id", mp("finance.bank", "delete"), handlers.DeleteBankAccount)
		protected.GET("/finance/vendor-invoices", mp("finance.ap", "view"), handlers.GetVendorInvoices)
		protected.POST("/finance/vendor-invoices", mp("finance.ap", "add"), handlers.CreateVendorInvoice)
		protected.PATCH("/finance/vendor-invoices/:id/status", mp("finance.ap", "edit"), handlers.UpdateVIStatus)
		protected.GET("/finance/payments-out", mp("finance.ap", "view"), handlers.GetPaymentsOut)
		protected.POST("/finance/payments-out", mp("finance.ap", "add"), handlers.CreatePaymentOut)
		protected.GET("/finance/payments-in", mp("finance.ar", "view"), handlers.GetPaymentsIn)
		protected.POST("/finance/payments-in", mp("finance.ar", "add"), handlers.CreatePaymentIn)
		protected.GET("/finance/aging-ap", mp("finance.aging-ap", "view"), handlers.GetAgingAP)
		protected.GET("/finance/aging-ar", mp("finance.aging-ar", "view"), handlers.GetAgingAR)
		protected.GET("/finance/cash-position", mp("finance.bank", "view"), handlers.GetCashPosition)

		// IoT (Phase 8)
		protected.GET("/iot/network/poll", mp("network.snmp", "view"), handlers.PollNetworkDevices)
		protected.GET("/iot/building/sensors", mp("building.overview", "view"), handlers.GetBuildingSensors)
		protected.GET("/iot/gps", handlers.GetGPSTracking)

		// Analytics (Phase 7)
		protected.GET("/analytics/summary", mp("analytics.executive", "view"), handlers.GetAnalyticsSummary)
		protected.GET("/analytics/role-dashboard", mp("analytics.executive", "view"), handlers.GetRoleDashboard)

		// Accounting (Phase 6) — ENT-02: admin/finance only
		accGroup := protected.Group("/accounting")
		accGroup.Use(middleware.RoleRequired("superadmin", "admin", "finance"))
		{
			accGroup.GET("/coa", mp("accounting.coa", "view"), handlers.GetCOA)
			accGroup.POST("/coa", mp("accounting.coa", "add"), handlers.CreateCOA)
			accGroup.GET("/journal", mp("accounting.journal", "view"), handlers.GetJournalEntries)
			accGroup.POST("/journal", mp("accounting.journal", "add"), handlers.CreateJournalEntry)
			accGroup.GET("/pl", mp("accounting.dashboard", "view"), handlers.GetProfitLoss)
			accGroup.GET("/balance-sheet", mp("accounting.dashboard", "view"), handlers.GetBalanceSheet)
		}
		// Security
		protected.GET("/security/visitors", mp("security.visitor", "view"), handlers.GetVisitors)
		protected.POST("/security/visitors", mp("security.visitor", "add"), handlers.CheckInVisitor)
		protected.PATCH("/security/visitors/:id/checkout", mp("security.visitor", "edit"), handlers.CheckOutVisitor)
		protected.GET("/security/incidents", mp("security.incident", "view"), handlers.GetIncidents)
		protected.POST("/security/incidents", mp("security.incident", "add"), handlers.CreateIncident)
		protected.PATCH("/security/incidents/:id/status", mp("security.incident", "edit"), handlers.UpdateIncidentStatus)

		// Vehicle
		protected.GET("/vehicle/fleet", mp("vehicle.fleet", "view"), handlers.GetFleet)
		protected.GET("/vehicle/fuel", mp("vehicle.fuel", "view"), handlers.GetFuelLogs)
		protected.POST("/vehicle/fuel", mp("vehicle.fuel", "add"), handlers.CreateFuelLog)

		// Network
		protected.GET("/network/devices", mp("network.devices", "view"), handlers.GetDevices)
		protected.PATCH("/network/devices/:id/toggle", mp("network.devices", "edit"), handlers.ToggleDevice)
		protected.GET("/network/traffic", mp("network.traffic", "view"), handlers.GetTraffic)

		// Notifications
		protected.GET("/notifications", handlers.GetNotifications)
		protected.PATCH("/notifications/:id/read", handlers.MarkNotificationRead)
		protected.DELETE("/notifications/clear", handlers.ClearNotifications)

		// BI & AI Analytics (Phase 21)
		protected.GET("/bi/demand-forecast", mp("analytics.forecast", "view"), handlers.GetDemandForecast)
		protected.GET("/bi/predictive-maintenance", mp("analytics.predictive", "view"), handlers.GetPredictiveMaintenance)
		protected.GET("/bi/anomalies", mp("analytics.anomalies", "view"), handlers.GetAnomalyDetection)
		protected.GET("/bi/price-recommendation", mp("analytics.price", "view"), handlers.GetPriceRecommendation)
		protected.GET("/bi/comparison", mp("analytics.comparison", "view"), handlers.GetComparisonReport)
		protected.POST("/bi/custom-report", mp("analytics.custom", "view"), handlers.GetCustomReport)
		protected.GET("/bi/scheduled-reports", mp("analytics.custom", "view"), handlers.GetScheduledReports)
		protected.POST("/bi/scheduled-reports", mp("analytics.custom", "add"), handlers.SaveScheduledReport)

		// Documents (Phase 20)
		protected.POST("/documents/upload", handlers.UploadDocument)
		protected.GET("/documents", handlers.GetDocuments)
		protected.DELETE("/documents/:id", handlers.DeleteDocument)

		// Multi-currency (Phase 20)
		protected.GET("/currency/list", mp("settings.currency", "view"), handlers.GetCurrencies)
		protected.POST("/currency/list", mp("settings.currency", "add"), handlers.CreateCurrency)
		protected.PUT("/currency/list/:id", mp("settings.currency", "edit"), handlers.UpdateCurrency)
		protected.GET("/currency/rates", mp("settings.currency", "view"), handlers.GetExchangeRates)
		protected.POST("/currency/rates", mp("settings.currency", "add"), handlers.SetExchangeRate)
		protected.GET("/currency/rates/latest", mp("settings.currency", "view"), handlers.GetLatestRates)

		// Notification Config (Phase 20)
		protected.GET("/settings/notif-config", mp("settings.notifications", "view"), handlers.GetNotifConfig)
		protected.PUT("/settings/notif-config", mp("settings.notifications", "edit"), handlers.SaveNotifConfig)
		protected.POST("/settings/notif-config/test-email", mp("settings.notifications", "view"), handlers.TestEmail)

		// ENT-06: Global search
		protected.GET("/search", handlers.GlobalSearch)

		// AI
		protected.POST("/ai/chat", handlers.AIChat)

		// Push Notifications (Phase 22)
		protected.GET("/push/vapid-key", handlers.GetVAPIDKey)
		protected.POST("/push/subscribe", handlers.SubscribePush)
		protected.DELETE("/push/subscribe", handlers.UnsubscribePush)
		protected.GET("/push/status", handlers.GetPushStatus)
		protected.POST("/push/send", handlers.SendPushNotification)

		// Security Lanjutan (Phase 30) — 2FA, Sessions, Audit Trail, Policy
		// NOTE: 2FA & Sessions are self-service (a user manages their OWN 2FA/sessions), not
		// organizational data — gated at "view" tier uniformly rather than add/edit, so anyone
		// who can reach the tab can still secure their own account regardless of tier.
		protected.GET("/security/2fa/status", mp("settings.2fa", "view"), handlers.Get2FAStatus)
		protected.POST("/security/2fa/setup", mp("settings.2fa", "view"), handlers.Setup2FA)
		protected.POST("/security/2fa/enable", mp("settings.2fa", "view"), handlers.Enable2FA)
		protected.POST("/security/2fa/disable", mp("settings.2fa", "view"), handlers.Disable2FA)
		protected.POST("/security/2fa/backup-codes/regenerate", mp("settings.2fa", "view"), handlers.RegenerateBackupCodes)
		protected.GET("/security/sessions", mp("settings.sessions", "view"), handlers.GetSessions)
		protected.DELETE("/security/sessions/:id", mp("settings.sessions", "view"), handlers.RevokeSession)
		protected.DELETE("/security/sessions", mp("settings.sessions", "view"), handlers.RevokeAllSessions)
		protected.GET("/security/audit-trail", mp("settings.audit", "view"), handlers.GetAuditTrail)
		protected.GET("/security/audit-trail/export", mp("settings.audit", "view"), handlers.ExportAuditTrail)
		protected.GET("/security/policy", mp("settings.security", "view"), handlers.GetSecurityPolicy)
		protected.PUT("/security/policy", mp("settings.security", "edit"), handlers.UpdateSecurityPolicy)

		// Customer & Vendor Portal (Phase 34)
		protected.GET("/portal/customers", handlers.GetPortalCustomers)
		protected.GET("/portal/vendors", handlers.GetPortalVendors)
		protected.GET("/portal/customer/dashboard", handlers.GetCustomerPortalDashboard)
		protected.GET("/portal/customer/orders", handlers.GetCustomerPortalOrders)
		protected.GET("/portal/customer/invoices", handlers.GetCustomerPortalInvoices)
		protected.GET("/portal/customer/deliveries", handlers.GetCustomerPortalDeliveries)
		protected.GET("/portal/vendor/dashboard", handlers.GetVendorPortalDashboard)
		protected.GET("/portal/vendor/pos", handlers.GetVendorPortalPOs)
		protected.GET("/portal/vendor/invoices", handlers.GetVendorPortalInvoices)
		protected.POST("/portal/vendor/invoices", handlers.CreatePortalVendorInvoice)
		protected.GET("/portal/vendor/payments", handlers.GetVendorPortalPayments)

		// Marketplace & IoT Hub (Phase 35)
		protected.GET("/marketplace/summary", mp("marketplace.overview", "view"), handlers.GetMarketplaceSummary)
		protected.GET("/marketplace/channels", mp("marketplace.channels", "view"), handlers.GetMarketplaceChannels)
		protected.GET("/marketplace/orders", mp("marketplace.orders", "view"), handlers.GetMarketplaceOrders)
		protected.POST("/marketplace/orders/:id/fulfill", mp("marketplace.orders", "edit"), handlers.FulfillMarketplaceOrder)
		protected.GET("/marketplace/listings", mp("marketplace.listings", "view"), handlers.GetProductListings)
		protected.POST("/marketplace/listings/sync", mp("marketplace.listings", "edit"), handlers.SyncProductListing)
		// IoT Hub
		protected.GET("/iot/devices", mp("iot.devices", "view"), handlers.GetIoTDevices)
		protected.POST("/iot/devices", mp("iot.devices", "add"), handlers.CreateIoTDevice)
		protected.PUT("/iot/devices/:id", mp("iot.devices", "edit"), handlers.UpdateIoTDevice)
		protected.DELETE("/iot/devices/:id", mp("iot.devices", "delete"), handlers.DeleteIoTDevice)
		protected.GET("/iot/readings", mp("iot.live", "view"), handlers.GetIoTReadings)
		protected.GET("/iot/alert-rules", mp("iot.alerts", "view"), handlers.GetIoTAlertRules)
		protected.POST("/iot/alert-rules", mp("iot.alerts", "add"), handlers.CreateIoTAlertRule)
		protected.DELETE("/iot/alert-rules/:id", mp("iot.alerts", "delete"), handlers.DeleteIoTAlertRule)
		protected.GET("/iot/alert-history", mp("iot.history", "view"), handlers.GetIoTAlertHistory)

		// Supply Chain Visibility & Traceability (Phase 36)
		protected.GET("/supply-chain/map", handlers.GetSupplyChainMap)
		protected.GET("/supply-chain/traceability", handlers.GetProductTraceability)
		protected.GET("/supply-chain/supplier-scorecard", handlers.GetSupplierScorecard)
		protected.GET("/supply-chain/risk", handlers.GetSupplyChainRisk)

		// Executive Dashboard & Management Reporting (Phase 37)
		protected.GET("/executive/dashboard", handlers.GetExecutiveDashboard)
		protected.GET("/executive/kpi-targets", handlers.GetKPITargets)
		protected.PUT("/executive/kpi-targets", handlers.UpdateKPITargets)
		protected.GET("/executive/management-report", handlers.GetManagementReport)
	}
}
