package routes

import (
	"sep/backend/internal/handlers"
	"sep/backend/internal/middleware"

	"github.com/gin-gonic/gin"
)

func Setup(r *gin.Engine, jwtSecret string) {
	// ENT-04: Global rate limit
	r.Use(middleware.RateLimit())

	v1 := r.Group("/api/v1")

	// Health & Readiness (Phase 23 — no auth required)
	v1.GET("/health", handlers.HealthCheck)
	v1.GET("/ready", handlers.ReadinessCheck)

	// IOT-01: WebSocket (no auth — client sends token after connect)
	r.GET("/ws", handlers.WSHandler)

	// Public routes (with auth-specific rate limit)
	auth := v1.Group("/auth")
	auth.Use(middleware.AuthRateLimit())
	{
		auth.POST("/login", handlers.Login)
	}

	// Protected routes
	protected := v1.Group("")
	protected.Use(middleware.AuthMiddleware(jwtSecret))
	{
		protected.POST("/auth/logout", handlers.Logout)
		protected.GET("/auth/me", handlers.Me)
		protected.PUT("/auth/password", handlers.ChangePassword)

		// RBAC & User Management (Phase 19)
		protected.GET("/rbac/users", handlers.GetUsers)
		protected.POST("/rbac/users", handlers.CreateUser)
		protected.PUT("/rbac/users/:id", handlers.UpdateUser)
		protected.PATCH("/rbac/users/:id/toggle-active", handlers.ToggleUserActive)
		protected.POST("/rbac/users/:id/reset-password", handlers.AdminResetPassword)
		protected.GET("/rbac/roles", handlers.GetRoles)
		protected.GET("/rbac/permissions", handlers.GetPermissions)
		protected.PUT("/rbac/roles/:role/permissions", handlers.UpdateRolePermissions)
		protected.GET("/rbac/access-logs", handlers.GetAccessLogs)
		protected.GET("/rbac/companies", handlers.GetCompanies)
		protected.POST("/rbac/companies", handlers.CreateCompany)

		// Dashboard
		protected.GET("/dashboard/kpi", handlers.DashboardKPI)
		protected.GET("/dashboard/alerts", handlers.DashboardAlerts)
		protected.GET("/dashboard/oee", handlers.OEERealtimeData)

		// Factory (Phase 5)
		protected.GET("/factory/workorders", handlers.GetWorkOrders)
		protected.POST("/factory/workorders", handlers.CreateWorkOrder)
		protected.PATCH("/factory/workorders/:id/qty", handlers.UpdateWorkOrderQty)
		protected.GET("/factory/machines", handlers.GetMachines)
		protected.POST("/factory/machines", handlers.CreateMachine)
		protected.PUT("/factory/machines/:id", handlers.UpdateMachine)
		protected.GET("/factory/bom", handlers.GetBOM)
		protected.POST("/factory/bom", handlers.CreateBOM)
		protected.GET("/factory/downtime", handlers.GetDowntime)
		protected.POST("/factory/downtime", handlers.CreateDowntime)

		// Factory Lanjutan (Phase 31) — Work Centers, Routing, OEE Real, Scrap, Capacity, Reports
		protected.GET("/factory/workcenters", handlers.GetWorkCenters)
		protected.POST("/factory/workcenters", handlers.CreateWorkCenter)
		protected.PUT("/factory/workcenters/:id", handlers.UpdateWorkCenter)
		protected.DELETE("/factory/workcenters/:id", handlers.DeleteWorkCenter)
		protected.GET("/factory/routings", handlers.GetProductRoutings)
		protected.POST("/factory/routings", handlers.CreateProductRouting)
		protected.PUT("/factory/routings/:id", handlers.UpdateProductRouting)
		protected.DELETE("/factory/routings/:id", handlers.DeleteProductRouting)
		protected.GET("/factory/oee-real", handlers.GetOEEReal)
		protected.GET("/factory/scrap", handlers.GetScrapRework)
		protected.POST("/factory/scrap", handlers.CreateScrapRework)
		protected.GET("/factory/capacity", handlers.GetCapacityPlan)
		protected.GET("/factory/report", handlers.GetProductionReport)
		protected.GET("/factory/downtime-analysis", handlers.GetDowntimeAnalysis)

		// HRIS
		protected.GET("/hris/employees", handlers.GetEmployees)
		protected.POST("/hris/employees", handlers.CreateEmployee)
		protected.PUT("/hris/employees/:id", handlers.UpdateEmployee)
		protected.DELETE("/hris/employees/:id", handlers.DeleteEmployee)
		protected.GET("/hris/attendance", handlers.GetAttendance)
		protected.POST("/hris/attendance/checkin", handlers.CheckInAttendance)
		protected.PATCH("/hris/attendance/:id/checkout", handlers.CheckOutAttendance)
		protected.GET("/hris/leaves", handlers.GetLeaveRequests)
		protected.POST("/hris/leaves", handlers.CreateLeaveRequest)
		protected.PATCH("/hris/leaves/:id/status", handlers.UpdateLeaveStatus)
		protected.GET("/hris/payroll", handlers.GetPayroll)
		protected.POST("/hris/payroll/generate", handlers.GeneratePayroll)
		protected.PATCH("/hris/payroll/:id/status", handlers.UpdatePayrollStatus)
		// HRIS Advanced (Phase 16)
		protected.GET("/hris/jobs", handlers.GetJobPostings)
		protected.POST("/hris/jobs", handlers.CreateJobPosting)
		protected.PATCH("/hris/jobs/:id/status", handlers.UpdateJobPosting)
		protected.DELETE("/hris/jobs/:id", handlers.DeleteJobPosting)
		protected.GET("/hris/candidates", handlers.GetCandidates)
		protected.POST("/hris/candidates", handlers.CreateCandidate)
		protected.PATCH("/hris/candidates/:id/stage", handlers.UpdateCandidateStage)
		protected.DELETE("/hris/candidates/:id", handlers.DeleteCandidate)
		protected.GET("/hris/training/programs", handlers.GetTrainingPrograms)
		protected.POST("/hris/training/programs", handlers.CreateTrainingProgram)
		protected.DELETE("/hris/training/programs/:id", handlers.DeleteTrainingProgram)
		protected.GET("/hris/training/schedules", handlers.GetTrainingSchedules)
		protected.POST("/hris/training/schedules", handlers.CreateTrainingSchedule)
		protected.PATCH("/hris/training/schedules/:id/status", handlers.UpdateTrainingStatus)
		protected.GET("/hris/kpi/templates", handlers.GetKPITemplates)
		protected.POST("/hris/kpi/templates", handlers.CreateKPITemplate)
		protected.DELETE("/hris/kpi/templates/:id", handlers.DeleteKPITemplate)
		protected.GET("/hris/kpi/reviews", handlers.GetKPIReviews)
		protected.POST("/hris/kpi/reviews", handlers.CreateKPIReview)
		protected.GET("/hris/shifts", handlers.GetShifts)
		protected.POST("/hris/shifts", handlers.CreateShift)
		protected.DELETE("/hris/shifts/:id", handlers.DeleteShift)
		protected.GET("/hris/overtime", handlers.GetOvertimeRecords)
		protected.POST("/hris/overtime", handlers.CreateOvertimeRecord)
		protected.PATCH("/hris/overtime/:id/status", handlers.UpdateOvertimeStatus)

		// HRIS Completion (Phase 32) — HR Dashboard, Org Chart, Payslip, Attendance Calendar
		protected.GET("/hris/dashboard", handlers.GetHRDashboard)
		protected.GET("/hris/orgchart", handlers.GetOrgChart)
		protected.GET("/hris/payslip", handlers.GetPayslipHistory)
		protected.GET("/hris/payslip/:id", handlers.GetPayslip)
		protected.GET("/hris/attendance-calendar", handlers.GetAttendanceCalendar)

		// Warehouse (Phase 4)
		protected.GET("/warehouse/inventory", handlers.GetInventory)
		protected.POST("/warehouse/inventory", handlers.CreateInventory)
		protected.PUT("/warehouse/inventory/:id", handlers.UpdateInventory)
		protected.DELETE("/warehouse/inventory/:id", handlers.DeleteInventory)
		protected.PUT("/warehouse/inventory/:id/qty", handlers.UpdateInventoryQty)
		protected.GET("/warehouse/movements", handlers.GetMovements)
		protected.POST("/warehouse/movements", handlers.CreateMovement)
		protected.GET("/warehouse/alerts", handlers.GetStockAlerts)
		protected.POST("/warehouse/transfer", handlers.CreateStockTransfer)
		protected.GET("/warehouse/opname", handlers.GetStockOpname)
		protected.POST("/warehouse/opname", handlers.SubmitStockOpname)

		// Asset
		protected.GET("/asset/assets", handlers.GetAssets)
		protected.POST("/asset/assets", handlers.CreateAsset)
		protected.PUT("/asset/assets/:id", handlers.UpdateAsset)
		protected.DELETE("/asset/assets/:id", handlers.DeleteAsset)
		protected.GET("/asset/maintenance", handlers.GetMaintenanceSchedule)
		protected.POST("/asset/maintenance", handlers.CreateMaintenance)
		protected.PATCH("/asset/maintenance/:id/status", handlers.UpdateMaintenanceStatus)
		// Asset CMMS (Phase 17)
		protected.GET("/asset/pm", handlers.GetPMSchedules)
		protected.POST("/asset/pm", handlers.CreatePMSchedule)
		protected.PUT("/asset/pm/:id", handlers.UpdatePMSchedule)
		protected.DELETE("/asset/pm/:id", handlers.DeletePMSchedule)
		protected.GET("/asset/spareparts", handlers.GetSpareParts)
		protected.POST("/asset/spareparts", handlers.CreateSparePart)
		protected.PUT("/asset/spareparts/:id", handlers.UpdateSparePart)
		protected.DELETE("/asset/spareparts/:id", handlers.DeleteSparePart)
		protected.GET("/asset/depreciation", handlers.GetDepreciation)
		protected.POST("/asset/depreciation/calculate", handlers.CalculateDepreciation)
		protected.GET("/asset/disposals", handlers.GetDisposals)
		protected.POST("/asset/disposals", handlers.CreateDisposal)

		// Purchasing
		protected.GET("/purchasing/pr", handlers.GetPurchaseRequests)
		protected.POST("/purchasing/pr", handlers.CreatePurchaseRequest)
		protected.PATCH("/purchasing/pr/:id/status", handlers.UpdatePRStatus)
		protected.POST("/purchasing/pr/:id/convert", handlers.ConvertPRtoPO)
		protected.DELETE("/purchasing/pr/:id", handlers.DeletePurchaseRequest)
		protected.GET("/purchasing/po", handlers.GetPurchaseOrders)
		protected.POST("/purchasing/po", handlers.CreatePurchaseOrder)
		protected.DELETE("/purchasing/po/:id", handlers.DeletePurchaseOrder)
		protected.GET("/purchasing/grn", handlers.GetGRN)
		protected.POST("/purchasing/grn", handlers.CreateGRN)
		protected.GET("/purchasing/vendors", handlers.GetVendors)
		protected.POST("/purchasing/vendors", handlers.CreateVendor)
		protected.PUT("/purchasing/vendors/:id", handlers.UpdateVendor)
		protected.DELETE("/purchasing/vendors/:id", handlers.DeleteVendor)

		// Sales (Phase 10)
		protected.GET("/sales/customers", handlers.GetCustomers)
		protected.POST("/sales/customers", handlers.CreateCustomer)
		protected.PUT("/sales/customers/:id", handlers.UpdateCustomer)
		protected.DELETE("/sales/customers/:id", handlers.DeleteCustomer)
		protected.GET("/sales/orders", handlers.GetSalesOrders)
		protected.POST("/sales/orders", handlers.CreateSalesOrder)
		protected.GET("/sales/orders/:id", handlers.GetSalesOrderDetail)
		protected.PATCH("/sales/orders/:id/status", handlers.UpdateSOStatus)
		protected.DELETE("/sales/orders/:id", handlers.DeleteSalesOrder)
		protected.GET("/sales/delivery", handlers.GetDeliveryOrders)
		protected.POST("/sales/delivery", handlers.CreateDelivery)
		protected.PATCH("/sales/delivery/:id/confirm", handlers.ConfirmDelivery)
		protected.GET("/sales/invoices", handlers.GetInvoices)
		protected.POST("/sales/invoices", handlers.CreateInvoice)

		// Sales Phase 24 — Quotation, Returns, CRM
		protected.GET("/sales/quotations", handlers.GetQuotations)
		protected.POST("/sales/quotations", handlers.CreateQuotation)
		protected.PATCH("/sales/quotations/:id/status", handlers.UpdateQuotationStatus)
		protected.POST("/sales/quotations/:id/convert", handlers.ConvertQuotationToSO)
		protected.GET("/sales/returns", handlers.GetSalesReturns)
		protected.POST("/sales/returns", handlers.CreateSalesReturn)
		protected.PATCH("/sales/returns/:id/confirm", handlers.ConfirmSalesReturn)
		protected.GET("/sales/crm/leads", handlers.GetLeads)
		protected.POST("/sales/crm/leads", handlers.CreateLead)
		protected.PUT("/sales/crm/leads/:id", handlers.UpdateLead)
		protected.PATCH("/sales/crm/leads/:id/stage", handlers.UpdateLeadStage)
		protected.GET("/sales/crm/activities", handlers.GetCRMActivities)
		protected.POST("/sales/crm/activities", handlers.CreateCRMActivity)
		protected.GET("/sales/crm/stats", handlers.GetCRMStats)

		// Quality Management (Phase 14)
		protected.GET("/qms/stats", handlers.GetQCStats)
		protected.GET("/qms/inspections", handlers.GetInspections)
		protected.POST("/qms/inspections", handlers.CreateInspection)
		protected.PATCH("/qms/inspections/:id/result", handlers.UpdateInspectionResult)
		protected.DELETE("/qms/inspections/:id", handlers.DeleteInspection)
		protected.GET("/qms/ncr", handlers.GetNCRs)
		protected.POST("/qms/ncr", handlers.CreateNCR)
		protected.PATCH("/qms/ncr/:id/status", handlers.UpdateNCRStatus)
		protected.DELETE("/qms/ncr/:id", handlers.DeleteNCR)
		protected.GET("/qms/capa", handlers.GetCAPAs)
		protected.POST("/qms/capa", handlers.CreateCAPA)
		protected.PATCH("/qms/capa/:id/status", handlers.UpdateCAPAStatus)
		protected.GET("/qms/tools", handlers.GetMeasuringTools)
		protected.POST("/qms/tools", handlers.CreateMeasuringTool)
		protected.PATCH("/qms/tools/:id/calibrate", handlers.RecordCalibration)
		protected.DELETE("/qms/tools/:id", handlers.DeleteMeasuringTool)
		protected.GET("/qms/calibration-alerts", handlers.GetCalibrationAlerts)

		// MRP & Production Planning (Phase 13)
		protected.GET("/mrp/runs", handlers.GetMRPRuns)
		protected.POST("/mrp/runs", handlers.RunMRP)
		protected.GET("/mrp/results", handlers.GetMRPResults)
		protected.GET("/mrp/exceptions", handlers.GetMRPExceptions)
		protected.GET("/mrp/schedules", handlers.GetProductionSchedules)
		protected.POST("/mrp/schedules", handlers.CreateProductionSchedule)
		protected.PATCH("/mrp/schedules/:id/status", handlers.UpdateScheduleStatus)
		protected.DELETE("/mrp/schedules/:id", handlers.DeleteProductionSchedule)
		protected.GET("/mrp/routings", handlers.GetRoutings)
		protected.POST("/mrp/routings", handlers.CreateRouting)
		protected.PUT("/mrp/routings/:id", handlers.UpdateRouting)
		protected.DELETE("/mrp/routings/:id", handlers.DeleteRouting)
		protected.GET("/mrp/lots", handlers.GetLotNumbers)
		protected.POST("/mrp/lots", handlers.CreateLotNumber)
		protected.DELETE("/mrp/lots/:id", handlers.DeleteLotNumber)

			// Cost Accounting (Phase 15)
			protected.GET("/cost/centers", handlers.GetCostCenters)
			protected.POST("/cost/centers", handlers.CreateCostCenter)
			protected.PUT("/cost/centers/:id", handlers.UpdateCostCenter)
			protected.DELETE("/cost/centers/:id", handlers.DeleteCostCenter)
			protected.GET("/cost/wo-costs", handlers.GetWOCosts)
			protected.POST("/cost/wo-costs", handlers.CreateWOCost)
			protected.DELETE("/cost/wo-costs/:id", handlers.DeleteWOCost)
			protected.GET("/cost/standard-costs", handlers.GetStandardCosts)
			protected.POST("/cost/standard-costs", handlers.UpsertStandardCost)
			protected.DELETE("/cost/standard-costs/:id", handlers.DeleteStandardCost)
			protected.GET("/cost/variance", handlers.GetCostVariance)
			protected.GET("/cost/cogs", handlers.GetCOGSReport)
			protected.GET("/cost/profitability", handlers.GetProfitabilityReport)
			protected.GET("/cost/center-report", handlers.GetCostCenterReport)
			protected.GET("/cost/summary", handlers.GetCostSummary)

			// Tax & Compliance (Phase 12)
		protected.GET("/tax/configs", handlers.GetTaxConfigs)
		protected.POST("/tax/configs", handlers.UpsertTaxConfig)
		protected.GET("/tax/faktur-keluaran", handlers.GetFakturPajakKeluaran)
		protected.GET("/tax/faktur-masukan", handlers.GetFakturPajakMasukan)
		protected.GET("/tax/ppn-rekap", handlers.GetRekapPPN)
		protected.GET("/tax/pph21", handlers.GetPPh21)
		protected.POST("/tax/pph21/generate", handlers.GeneratePPh21)
		protected.DELETE("/tax/pph21/:id", handlers.DeletePPh21)
		protected.GET("/tax/pph23", handlers.GetPPh23)
		protected.POST("/tax/pph23", handlers.CreatePPh23)
		protected.DELETE("/tax/pph23/:id", handlers.DeletePPh23)
		protected.GET("/tax/bpjs", handlers.GetBPJS)
		protected.POST("/tax/bpjs/generate", handlers.GenerateBPJS)
		protected.DELETE("/tax/bpjs/:id", handlers.DeleteBPJS)

		// Budget & Financial Planning (Phase 18)
		protected.GET("/budget/entries", handlers.GetBudgets)
		protected.POST("/budget/entries", handlers.CreateBudget)
		protected.POST("/budget/entries/import", handlers.ImportBudgetEntries)
		protected.GET("/budget/entries/template", handlers.GetBudgetTemplate)
		protected.PUT("/budget/entries/:id", handlers.UpdateBudget)
		protected.DELETE("/budget/entries/:id", handlers.DeleteBudget)
		protected.PATCH("/budget/entries/:id/submit", handlers.SubmitBudget)
		protected.PATCH("/budget/entries/:id/approve", handlers.ApproveBudget)
		protected.PATCH("/budget/entries/:id/reject", handlers.RejectBudget)
		protected.GET("/budget/vs-actual", handlers.GetBudgetVsActual)
		protected.GET("/budget/alerts", handlers.GetBudgetAlerts)
		protected.GET("/budget/forecast", handlers.GetBudgetForecast)
		protected.GET("/budget/scenarios", handlers.GetBudgetScenarios)
		protected.POST("/budget/scenarios", handlers.CreateBudgetScenario)
		protected.PUT("/budget/scenarios/:id", handlers.UpdateBudgetScenario)
		protected.DELETE("/budget/scenarios/:id", handlers.DeleteBudgetScenario)

		// Import / Export & API Publik (Phase 29)
		protected.GET("/integration/import/templates", handlers.GetImportTemplates)
		protected.GET("/integration/import/templates/:type/download", handlers.DownloadTemplate)
		protected.POST("/integration/import/preview", handlers.PreviewImport)
		protected.POST("/integration/import/execute", handlers.ExecuteImport)
		protected.GET("/integration/import/history", handlers.GetImportHistory)
		protected.GET("/integration/export/:type", handlers.ExportData)
		protected.GET("/integration/api-keys", handlers.GetAPIKeys)
		protected.POST("/integration/api-keys", handlers.CreateAPIKey)
		protected.DELETE("/integration/api-keys/:id", handlers.RevokeAPIKey)
		protected.GET("/integration/api-keys/logs", handlers.GetAPIUsageLogs)
		protected.GET("/integration/webhooks", handlers.GetWebhooks)
		protected.POST("/integration/webhooks", handlers.CreateWebhook)
		protected.PUT("/integration/webhooks/:id", handlers.UpdateWebhook)
		protected.DELETE("/integration/webhooks/:id", handlers.DeleteWebhook)
		protected.GET("/integration/webhooks/:id/logs", handlers.GetWebhookLogs)
		protected.GET("/integration/webhook-events", handlers.GetWebhookEvents)

		// Coretax DJP & e-Faktur (Phase 28)
		protected.GET("/tax/nsfp", handlers.GetNSFP)
		protected.POST("/tax/nsfp/import", handlers.ImportNSFP)
		protected.GET("/tax/efaktur", handlers.GetEFaktur)
		protected.GET("/tax/efaktur/:id/xml", handlers.GetEFakturXML)
		protected.GET("/tax/efaktur/export-csv", handlers.ExportEFakturCSV)
		protected.POST("/tax/efaktur/:id/upload", handlers.UploadEFakturCoretax)
		protected.GET("/tax/spt-ppn", handlers.GetSPTPPN)
		protected.POST("/tax/spt-ppn/submit", handlers.SubmitSPTPPN)

		// Bank Rekonsiliasi & Petty Cash (Phase 27)
		protected.GET("/recon/sessions", handlers.GetReconSessions)
		protected.POST("/recon/sessions", handlers.CreateReconSession)
		protected.GET("/recon/sessions/:id", handlers.GetReconDetail)
		protected.POST("/recon/sessions/:id/auto-match", handlers.AutoMatch)
		protected.POST("/recon/sessions/:id/manual-match", handlers.ManualMatch)
		protected.PATCH("/recon/sessions/:id/lock", handlers.LockRecon)
		protected.GET("/petty-cash", handlers.GetPettyCash)
		protected.POST("/petty-cash", handlers.CreatePettyCash)
		protected.GET("/petty-cash/transactions", handlers.GetPettyCashTransactions)
		protected.POST("/petty-cash/transactions", handlers.CreatePettyCashTransaction)
		protected.POST("/petty-cash/:id/replenish", handlers.ReplenishPettyCash)

		// Finance GL & Closing (Phase 25)
		protected.GET("/finance/gl", handlers.GetGeneralLedger)
		protected.GET("/finance/trial-balance", handlers.GetTrialBalance)
		protected.GET("/finance/cashflow", handlers.GetCashFlow)
		protected.GET("/finance/periods", handlers.GetAccountingPeriods)
		protected.PATCH("/finance/periods/:id/close", handlers.ClosePeriod)
		protected.PATCH("/finance/periods/:id/reopen", handlers.ReopenPeriod)
		protected.GET("/finance/comparative/income-statement", handlers.GetComparativeIncomeStatement)
		protected.GET("/finance/comparative/balance-sheet", handlers.GetComparativeBalanceSheet)

		// Finance — AP/AR/Cash (Phase 11)
		protected.GET("/finance/bank-accounts", handlers.GetBankAccounts)
		protected.POST("/finance/bank-accounts", handlers.CreateBankAccount)
		protected.PUT("/finance/bank-accounts/:id", handlers.UpdateBankAccount)
		protected.DELETE("/finance/bank-accounts/:id", handlers.DeleteBankAccount)
		protected.GET("/finance/vendor-invoices", handlers.GetVendorInvoices)
		protected.POST("/finance/vendor-invoices", handlers.CreateVendorInvoice)
		protected.PATCH("/finance/vendor-invoices/:id/status", handlers.UpdateVIStatus)
		protected.GET("/finance/payments-out", handlers.GetPaymentsOut)
		protected.POST("/finance/payments-out", handlers.CreatePaymentOut)
		protected.GET("/finance/payments-in", handlers.GetPaymentsIn)
		protected.POST("/finance/payments-in", handlers.CreatePaymentIn)
		protected.GET("/finance/aging-ap", handlers.GetAgingAP)
		protected.GET("/finance/aging-ar", handlers.GetAgingAR)
		protected.GET("/finance/cash-position", handlers.GetCashPosition)

		// IoT (Phase 8)
		protected.GET("/iot/network/poll", handlers.PollNetworkDevices)
		protected.GET("/iot/building/sensors", handlers.GetBuildingSensors)
		protected.GET("/iot/gps", handlers.GetGPSTracking)

		// Analytics (Phase 7)
		protected.GET("/analytics/summary", handlers.GetAnalyticsSummary)
		protected.GET("/analytics/role-dashboard", handlers.GetRoleDashboard)

		// Accounting (Phase 6) — ENT-02: admin/finance only
		accGroup := protected.Group("/accounting")
		accGroup.Use(middleware.RoleRequired("superadmin", "admin", "finance"))
		{
			accGroup.GET("/coa", handlers.GetCOA)
			accGroup.POST("/coa", handlers.CreateCOA)
			accGroup.GET("/journal", handlers.GetJournalEntries)
			accGroup.POST("/journal", handlers.CreateJournalEntry)
			accGroup.GET("/pl", handlers.GetProfitLoss)
			accGroup.GET("/balance-sheet", handlers.GetBalanceSheet)
		}
		// Security
		protected.GET("/security/visitors", handlers.GetVisitors)
		protected.POST("/security/visitors", handlers.CheckInVisitor)
		protected.PATCH("/security/visitors/:id/checkout", handlers.CheckOutVisitor)
		protected.GET("/security/incidents", handlers.GetIncidents)
		protected.POST("/security/incidents", handlers.CreateIncident)
		protected.PATCH("/security/incidents/:id/status", handlers.UpdateIncidentStatus)

		// Vehicle
		protected.GET("/vehicle/fleet", handlers.GetFleet)
		protected.GET("/vehicle/fuel", handlers.GetFuelLogs)
		protected.POST("/vehicle/fuel", handlers.CreateFuelLog)

		// Network
		protected.GET("/network/devices", handlers.GetDevices)
		protected.PATCH("/network/devices/:id/toggle", handlers.ToggleDevice)
		protected.GET("/network/traffic", handlers.GetTraffic)

		// Notifications
		protected.GET("/notifications", handlers.GetNotifications)
		protected.PATCH("/notifications/:id/read", handlers.MarkNotificationRead)
		protected.DELETE("/notifications/clear", handlers.ClearNotifications)

		// BI & AI Analytics (Phase 21)
		protected.GET("/bi/demand-forecast", handlers.GetDemandForecast)
		protected.GET("/bi/predictive-maintenance", handlers.GetPredictiveMaintenance)
		protected.GET("/bi/anomalies", handlers.GetAnomalyDetection)
		protected.GET("/bi/price-recommendation", handlers.GetPriceRecommendation)
		protected.GET("/bi/comparison", handlers.GetComparisonReport)
		protected.POST("/bi/custom-report", handlers.GetCustomReport)
		protected.GET("/bi/scheduled-reports", handlers.GetScheduledReports)
		protected.POST("/bi/scheduled-reports", handlers.SaveScheduledReport)

		// Documents (Phase 20)
		protected.POST("/documents/upload", handlers.UploadDocument)
		protected.GET("/documents", handlers.GetDocuments)
		protected.DELETE("/documents/:id", handlers.DeleteDocument)

		// Multi-currency (Phase 20)
		protected.GET("/currency/list", handlers.GetCurrencies)
		protected.POST("/currency/list", handlers.CreateCurrency)
		protected.PUT("/currency/list/:id", handlers.UpdateCurrency)
		protected.GET("/currency/rates", handlers.GetExchangeRates)
		protected.POST("/currency/rates", handlers.SetExchangeRate)
		protected.GET("/currency/rates/latest", handlers.GetLatestRates)

		// Notification Config (Phase 20)
		protected.GET("/settings/notif-config", handlers.GetNotifConfig)
		protected.PUT("/settings/notif-config", handlers.SaveNotifConfig)
		protected.POST("/settings/notif-config/test-email", handlers.TestEmail)

		// ENT-06: Global search
		protected.GET("/search", handlers.GlobalSearch)

		// AI
		protected.POST("/ai/chat", handlers.AIChat)

		// Push Notifications (Phase 22)
		protected.GET("/push/vapid-key", handlers.GetVAPIDKey)
		protected.POST("/push/subscribe", handlers.SubscribePush)
		protected.DELETE("/push/subscribe", handlers.UnsubscribePush)
		protected.GET("/push/status", handlers.GetPushStatus)
		protected.POST("/push/send", handlers.SendPushNotification)

		// Security Lanjutan (Phase 30) — 2FA, Sessions, Audit Trail, Policy
		protected.GET("/security/2fa/status", handlers.Get2FAStatus)
		protected.POST("/security/2fa/setup", handlers.Setup2FA)
		protected.POST("/security/2fa/enable", handlers.Enable2FA)
		protected.POST("/security/2fa/disable", handlers.Disable2FA)
		protected.POST("/security/2fa/backup-codes/regenerate", handlers.RegenerateBackupCodes)
		protected.GET("/security/sessions", handlers.GetSessions)
		protected.DELETE("/security/sessions/:id", handlers.RevokeSession)
		protected.DELETE("/security/sessions", handlers.RevokeAllSessions)
		protected.GET("/security/audit-trail", handlers.GetAuditTrail)
		protected.GET("/security/audit-trail/export", handlers.ExportAuditTrail)
		protected.GET("/security/policy", handlers.GetSecurityPolicy)
		protected.PUT("/security/policy", handlers.UpdateSecurityPolicy)

		// Customer & Vendor Portal (Phase 34)
		protected.GET("/portal/customers", handlers.GetPortalCustomers)
		protected.GET("/portal/vendors", handlers.GetPortalVendors)
		protected.GET("/portal/customer/dashboard", handlers.GetCustomerPortalDashboard)
		protected.GET("/portal/customer/orders", handlers.GetCustomerPortalOrders)
		protected.GET("/portal/customer/invoices", handlers.GetCustomerPortalInvoices)
		protected.GET("/portal/customer/deliveries", handlers.GetCustomerPortalDeliveries)
		protected.GET("/portal/vendor/dashboard", handlers.GetVendorPortalDashboard)
		protected.GET("/portal/vendor/pos", handlers.GetVendorPortalPOs)
		protected.GET("/portal/vendor/invoices", handlers.GetVendorPortalInvoices)
		protected.POST("/portal/vendor/invoices", handlers.CreatePortalVendorInvoice)
		protected.GET("/portal/vendor/payments", handlers.GetVendorPortalPayments)

		// Marketplace & IoT Hub (Phase 35)
		protected.GET("/marketplace/summary", handlers.GetMarketplaceSummary)
		protected.GET("/marketplace/channels", handlers.GetMarketplaceChannels)
		protected.GET("/marketplace/orders", handlers.GetMarketplaceOrders)
		protected.POST("/marketplace/orders/:id/fulfill", handlers.FulfillMarketplaceOrder)
		protected.GET("/marketplace/listings", handlers.GetProductListings)
		protected.POST("/marketplace/listings/sync", handlers.SyncProductListing)
		// IoT Hub
		protected.GET("/iot/devices", handlers.GetIoTDevices)
		protected.POST("/iot/devices", handlers.CreateIoTDevice)
		protected.PUT("/iot/devices/:id", handlers.UpdateIoTDevice)
		protected.DELETE("/iot/devices/:id", handlers.DeleteIoTDevice)
		protected.GET("/iot/readings", handlers.GetIoTReadings)
		protected.GET("/iot/alert-rules", handlers.GetIoTAlertRules)
		protected.POST("/iot/alert-rules", handlers.CreateIoTAlertRule)
		protected.DELETE("/iot/alert-rules/:id", handlers.DeleteIoTAlertRule)
		protected.GET("/iot/alert-history", handlers.GetIoTAlertHistory)

		// Supply Chain Visibility & Traceability (Phase 36)
		protected.GET("/supply-chain/map", handlers.GetSupplyChainMap)
		protected.GET("/supply-chain/traceability", handlers.GetProductTraceability)
		protected.GET("/supply-chain/supplier-scorecard", handlers.GetSupplierScorecard)
		protected.GET("/supply-chain/risk", handlers.GetSupplyChainRisk)

		// Executive Dashboard & Management Reporting (Phase 37)
		protected.GET("/executive/dashboard", handlers.GetExecutiveDashboard)
		protected.GET("/executive/kpi-targets", handlers.GetKPITargets)
		protected.PUT("/executive/kpi-targets", handlers.UpdateKPITargets)
		protected.GET("/executive/management-report", handlers.GetManagementReport)
	}
}
